### ISSUE TITLE
March 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Security-baseline-on-Azure#14]
@joelhulen @kylebunting 
Solliance team - 
This workshop is scheduled for an update in March.  We will be combining this workshop with the Azure security and management workshop.  Please update this issue with suggested content changes.  Once done, we'll assign to our SME team for review and additional feedback.

**Comment by givenscj** [comment]
Here is my list (if we are moving the other MCW into this one) of what I'd save/integrate into this MCW:

Update Management and Change Tracking (VMs)
Application Insights installed on VM (IIS request\app tracking)
Mobile push of insights based alert message (mobile app)

**Comment by ChongRX78** [comment]
Incorporate design principles used in Cloud Adoption Framework - examples below:
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/large-enterprise/security-baseline-evolution
https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/decision-guides/policy-enforcement/overview

**Comment by ChongRX78** [comment]
Add new capabilities in Azure Sentinel: https://azure.microsoft.com/en-us/services/azure-sentinel/

**Comment by ChongRX78** [comment]
Scenarios using Azure Lockbox: https://azure.microsoft.com/en-us/blog/approve-audit-support-access-requests-to-vms-using-customer-lockbox-for-azure/

**Comment by jknightly** [comment]
It'd be great to have part of the lab to see the secure score before and after configuration is done, but policy refresh will be an issue. Maybe at least note the secure score and explain it so students are aware of it? https://docs.microsoft.com/en-us/azure/security-center/security-center-secure-score

**Comment by jknightly** [comment]
Consider replacing the compliance/powerBI section with the regulatory compliance dashboard (or add the dashboard separately) https://azure.microsoft.com/en-us/blog/regulatory-compliance-dashboard-in-azure-security-center-now-available/

**Comment by DawnmarieDesJardins** [comment]
Closing issue with March 2019 update merge.
