### ISSUE TITLE
Please add DDoS Link

### ISSUE THREAD

**Issue by ChongRX78** [Microsoft/MCW-Security-baseline-on-Azure#17]
Please add this link to the WDS Student Guide:  https://docs.microsoft.com/en-us/azure/virtual-network/ddos-protection-overview for DDoS.

Thank you!

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris, can you double check that this has been added please?  Thanks, Dawnmarie

**Comment by givenscj** [comment]
Done.
