### ISSUE TITLE
Issues in Exercise 5

### ISSUE THREAD

**Issue by Suraj2093** [microsoft/MCW-Security-baseline-on-Azure#20]
1.In Exercise 5 Task 1 : In Step 3 we are asked to select the Log Analytics resource but we don't have one. So we have to create a LogAnalytics Workspace 1st which is not mentioned in the lab guide.
2.Exercise 5 Task 2 : Was not able to complete since Set Alert Query given is wrong
![image](https://user-images.githubusercontent.com/30050847/57257717-dc3e4b80-7077-11e9-989f-b2cf08911a2b.png)
3.Exercise 5 Task 4 : In step 7 we are asked to sign in to O365 account for receiving email Azure Security Center, but I don't receive any mails. Is an O365 account really required for this lab.
4.Exercise 5 Task 6 : In step 3 we are asked to open **AzureDiagnostics** which is not available in the list.

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris!  Please review and advise.  This workshop is scheduled for delivery on 5/15.  
Thanks, Dawnmarie

**Comment by givenscj** [comment]
Hi there,

Can you confirm that you have the latest commit from the repo for the azure ARM template?  It creates the Log Analytics workspace.  You may have grabbed a version before we did an update.

Logs (AzureDiagnostics) take a while to populate after you setup the diagnostics logs.  You won't get results until you have generated data via the port scan script.

Additionally the alert will not fire for 30 minutes, however you could reduce the time.

Thanks,
Chris

**Comment by Suraj2093** [comment]
Hi Chris,

I have used the latest template from the Git https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/Scripts/template.json , it is not deploying the Log Analytics Workspace. Can you please check and revert.

Thanks,
Suraj Pai

**Comment by givenscj** [comment]
Ah, I see what the deal is, we have two ARM templates in the repo.  I'll converge the two, thanks.

**Comment by givenscj** [comment]
Templates are updated.  Pull request merged.
