### ISSUE TITLE
Issues in Service Trust/Compliance Manager portal in Exercise 6

### ISSUE THREAD

**Issue by Suraj2093** [microsoft/MCW-Security-baseline-on-Azure#21]
1.Exercise 6 Task 4 : The UI Service Trust/Compliance Manager portal have changed a bit so please make the required changes, like creating a new group is asking more info as mentioned below.
![image](https://user-images.githubusercontent.com/30050847/57258170-49061580-7079-11e9-8fc0-0e6a96beb678.png)

**Comment by DawnmarieDesJardins** [comment]
@givenscj 
Hi Chris!  Please review and advise.  This workshop is scheduled for delivery on 5/15.  
Thanks, Dawnmarie

**Comment by givenscj** [comment]
Compliance Manager v3 doesn't support Azure right now but I did update the screen shots to tell workshop attendees to go to classic.

**Comment by Suraj2093** [comment]
Hello,

I don't see any updates on the screenshots, can someone please merge the changes so that I can test this part.

Thanks,
Suraj Pai
