### ISSUE TITLE
Before the Hands-On Lab- Task 2. deploy template error

### ISSUE THREAD

**Issue by daveRendon** [microsoft/MCW-Security-baseline-on-Azure#23]
Error: An invalid value was provided for 'accessPolicies'

{ "id": "/subscriptions/6618f5bd-7a40-4584-8a49-653c870e835c/resourceGroups/azsecurity-dr/providers/Microsoft.Resources/deployments/Microsoft.Template/operations/712FE71A26BC9911", "operationId": "712FE71A26BC9911", "properties": { "provisioningOperation": "Create", "provisioningState": "Failed", "timestamp": "2019-05-22T00:45:10.9057516Z", "duration": "PT0.655914S", "trackingId": "9b0b8e89-e127-4a03-acee-9bedf62fd50d", "serviceRequestId": "570ed2c2-d888-49e0-ac75-46765e070273", "statusCode": "BadRequest", "statusMessage": { "error": { "code": "BadRequest", "message": "An invalid value was provided for 'accessPolicies'." } }, "targetResource": { "id": "/subscriptions/6618f5bd-7a40-4584-8a49-653c870e835c/resourceGroups/azsecurity-dr/providers/Microsoft.KeyVault/vaults/kvpbclh5l2bei34", "resourceType": "Microsoft.KeyVault/vaults", "resourceName": "kvpbclh5l2bei34" }, "response": { "content": { "error": { "code": "BadRequest", "message": "An invalid value was provided for 'accessPolicies'." } } } }}

**Comment by DawnmarieDesJardins** [comment]
@givenscj @timahenning 
Hello!
Please review and advise.
Thanks, Dawnmarie

**Comment by timahenning** [comment]
Chris will look into this today.

Tim

**Comment by givenscj** [comment]
Hi Dave, I just deployed the template and it ran fine.  Make sure you copied the correct "objectId" for your user account into the parameter field.

**Comment by daveRendon** [comment]
thanks for the follow up and quick response @DawnmarieDesJardins @givenscj was able to move forward with the lab. Thanks!

**Comment by DawnmarieDesJardins** [comment]
Spectacular!  Closing issue as resolved.
