### ISSUE TITLE
Change from waiting on recommendation for JIT to set JIT on the VM.

### ISSUE THREAD

**Issue by mwasham** [microsoft/MCW-Security-baseline-on-Azure#24]
ASC takes any where from 10 minutes to an hour+ to recommend JIT access on a VM.

The lab should be updated to highlight that yes ASC will eventually recommend it, but to go into each VM click -> Configure -> Emable JIT to speed up the process.

**Comment by DawnmarieDesJardins** [comment]
@waltermyersiii @givenscj @timahenning 
Hello,
Please review & advise.  My information is that this is something that should not wait for the next update cycle due to usable consistency for different learners.  
Thanks, Dawnmarie

**Comment by givenscj** [comment]
Hi,

I have not personally seen it take an hour before, but then again, some regions may very well experience that.  We can rework the lab to force the setting as a NOTE after x minutes.

**Comment by givenscj** [comment]
Added new NOTE text and image.
