### ISSUE TITLE
Warning: Unique name on resource

### ISSUE THREAD

**Issue by daveRendon** [microsoft/MCW-Security-baseline-on-Azure#25]
Suggestion: add a note on the lab to ensure that the workspace name is unique and modify it on the template before provisioning: 

{
  "error": {
    "code": "Conflict",
    "message": "The workspace name 'azsecuritylogging' is not unique",
    "target": "name"
  }
}

On the template - \Hands-on lab\Scripts\template.json- line 38:

"resources": [
    {
      "type": "microsoft.operationalinsights/workspaces",
      "name": "**azsecuritylogging**",
      "apiVersion": "2015-11-01-preview",
      "location": "eastus",
      "scale": null,
      "properties": {
          "sku": {
              "name": "standalone"
          },
          "retentionInDays": 31
      },

**Comment by DawnmarieDesJardins** [comment]
Labelling issue as an enhancement to be incorporated at next scheduled update.
Thanks @daveRendon

**Comment by mathieu-benoit** [comment]
FYI: Since it's an error while deploying, I have submitted this PR #26 to fix the ARM Template.

**Comment by givenscj** [comment]
Thanks!
