### ISSUE TITLE
Example Analytics Query doesn't trigger

### ISSUE THREAD

**Issue by x3nc0n** [microsoft/MCW-Security-baseline-on-Azure#29]
The example analytics Kusto query doesn't ever seem to fire.

`AzureDiagnostics | where Type != 'AzureMetric' and OperationName == 'NetworkSecurityGroupCounters' and type_s == 'block' and direction_s == 'In' and Resource == 'WEBTRAFFICONLY'`

I don't think this query is doing what we want in the HOL. We need to check for any results where a rule counter is triggers higher than usual. The above query will always return the same number of results regardless of scanning activity.

**Comment by givenscj** [comment]
Hi there,  this query is the count of NSG port blocks.  I believe you may be right about the same number of "total" results as it doesn't seem to have a date limit on it.  Checking on this.

That being said, if true, the count would always go up so you'd eventually see it fire, as I'm sure you are aware, it does take some time for the events to make it into LogAnalytics.

**Comment by givenscj** [comment]
Added the "and TimeGenerated > ago(1h)" to the existing query.  Thanks.
