### ISSUE TITLE
Exercise 5 (task 5)

### ISSUE THREAD

**Issue by srushti-714** [microsoft/MCW-Security-baseline-on-Azure#35]
Error in the jupyter notebook 's command
Below is the attached screenshot.

![2019-10-25_19-06-15](https://user-images.githubusercontent.com/55180169/67653764-e4b17800-f970-11e9-9792-674b2c61ea5a.png)

**Comment by givenscj** [comment]
Unfortunately, this is on the product group side.  I'll need to research and see if I can submit a pull request to that repo.
