### ISSUE TITLE
Needs LabVM

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#39]
Lab requires user to have access to
- Visual Studio 2019
- SQL Management Studio
- Power BI Desktop

That's simply not realistic. Some users are unwilling or unable to install these services. and some use MacOS.

The lab should instead provide a LabVM with all the necessary SW pre-installed.

**Comment by givenscj** [comment]
Thanks, we will look at adding a LabVM step in the next enhancement/update cycle.

**Comment by givenscj** [comment]
Latest workshop now has a LabVM.  It will be committed today then reviewed and released in the next few days.
