### ISSUE TITLE
Lab broken (Ex 2)

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#40]
Exercise 2, Task 2, Step 5
Application doesn't work! See image below. Cleaning/re-building doesn't help.
Am fairly sure it's not a mistake I made since I have a classroom full of students experiencing the same issue.

![image](https://user-images.githubusercontent.com/8792554/70717097-94566580-1ce5-11ea-8c27-d3151afcb73d.png)

**Comment by givenscj** [comment]
This is a common error related to nuget packages around the .net compiler.  We will add steps to show how to resolve if you run across this for future.

**Comment by timahenning** [comment]
I just ran the lab and received the same error for Visual Studio 2019.  I followed the instructions of Cleaning and Rebuilding the API project.  I did not see the error after running the project again.

![image](https://user-images.githubusercontent.com/48766586/71136259-13054400-21b9-11ea-9d37-696cac1513da.png)

**Comment by jtuliani** [comment]
Having a LabVM so everyone is on an identical VS version should help make this deterministic, so the lab 'just works' rather than requiring troubleshooting?

**Comment by timahenning** [comment]
I am going to include a package manager command to reinstall DotNetCompilerPlatform in a fix.  This should help as well.

**Comment by jtuliani** [comment]
Tried this with VS Community 2019 on WS2019 Azure VM (latest version in marketplace)
Same error
Rebuild alone does not fix
Clean followed by rebuild **DOES** fix
Suggest putting explicit instructions to clean + rebuild into the lab (not just as a troubleshooting tip)

**Comment by DawnmarieDesJardins** [comment]
Closing with PR #46
