### ISSUE TITLE
lab issues

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#42]
Ex 2 Task 1 Step 9
Need to explain how to open New Firewall Rule dialog, it's not obvious and doesn't open automaticaly.

Ex 3 Task 4
Refers to Client ID from Task 2. But Task 2 doesn't mention a Client ID. It only mentions an Application ID. Confusing.

**Comment by givenscj** [comment]
I have never had an instance where it didn't automatically show up, but possible newer versions of SQL Server management studio don't have it anymore.  We'll add some portal based steps for future.

**Comment by timahenning** [comment]
I just selected the Connect button and the Firewall Rule dialog popped up.

![image](https://user-images.githubusercontent.com/48766586/71134494-5e1c5880-21b3-11ea-86a0-4d4669c7f124.png)

**Comment by timahenning** [comment]
The ClientId is now ApplicationId.  The Azure UI has it in parenthesis.

![image](https://user-images.githubusercontent.com/48766586/71228944-a82b3a00-2298-11ea-920e-56b350083b6b.png)

I can see how this could be confusing and I have updated the instructions to be clearer.  Thank you for the suggestion.

**Comment by DawnmarieDesJardins** [comment]
Closing with merge of PR
