### ISSUE TITLE
Azure Sentinel section broken

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#43]
Couldn't get AzureSentinel part of lab to work at all. Needs accurate instructions, more screenshots, and needs to be fixed. Any timing sensitive issues (e.g. time for log data to appear) need to be called out.

**Comment by givenscj** [comment]
I didn't have any issues when I did this a few weeks back, but we will take a look on the next update cycle.  Sentinel is a continually changing product and its release cadence is rather high at the moment.

**Comment by jtuliani** [comment]
Examples of issues (there may be more, it needs careful review):
 - Task 2 step 9: Refers to 'suppress alerts' option, not in Portal
 - Task 4 step 5: Says to use 'Send notification email' template, but no such exists

**Comment by timahenning** [comment]
I went through the Azure Sentinel portion of the lab and added some more updated screenshots and instructions.  I will be publishing the updates in the next couple of days.

**Comment by jtuliani** [comment]
Sounds good. I'm teaching this lab on Thursday (Europe time zone), so updates before then would be super. Thanks!

**Comment by timahenning** [comment]
@jtuliani If you have a tight deadline, I would pull from my fork for review while we QC and merge.  The material should not change drastically.

**Comment by DawnmarieDesJardins** [comment]
Closing with PR merge
