### ISSUE TITLE
Exercise 3 confusing/incomplete

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#45]
This exercise covers two kinds of Key Vault usage - column encryption, and storing the connection string.

At the end of the exercise, I'd expect to see the app working. But it doesn't! Task 5 step 5 just says "Because you encrypted the column in the previous exercise, EntityFramework is not able to retrieve the value. You would need to...."

It's as if the lab is incomplete.

It would be MUCH better if the exercise was split in two, and fully implemented / validated at each step. E.g.
 - Do the column encryption, get the app working, validate it
 - Move the connection string to KeyVault, get the app working again, validate it.

Ex 2 Task 3
Nice to show data masking. But should also show how an app that needs the data can still get the unmasked data

**Comment by givenscj** [comment]
The original version of the SDK for this had conflicts with other NuGet packages.  So it was left for another day when they would finally all play nice with each other.  I just reviewed the latest and it has now stabilized.  I have added a 3rd solution that has the necessary references and code to allow Entity Framework to make the queries and displayed the seamlessly decrypted data.  Will be committed later today and then available in a few days.
