### ISSUE TITLE
Out of date info in WDS trainer guide

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Security-baseline-on-Azure#47]
Trainer Guide includes:

_Alternately, an Azure Web App could be used to host the data collection web site, but not the corporate website (because Azure Web Apps does not offer any configuration that provides private, virtual network only endpoints, at least until App Service Environments leave preview). Cloud Services were ruled out so that Contoso could avoid changes to their development and deployment experience_

That's very out of date! Please review rest of WDS materials similarly

**Comment by timahenning** [comment]
Thank you for the suggestion.  We will review this for the next update.

**Comment by givenscj** [comment]
Thanks for pointing this out, lots of recent developments on this so we'll find a place to work some of the new service end points and vnet changes into the scenario as options.  This sentence will be remove from the next commit.
