### ISSUE TITLE
Virtual machine extension is not working for "web-1"

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Security-baseline-on-Azure#52]
The extension for the virtual machine "web-1" which is used to install InstallIIS is not working it is failing. I have also tried manually to run that script but it was not working .

**Comment by givenscj** [comment]
Hi,  I just ran the ARM template and everything installed fine.  The zip file contains the script that is run and it is simply an install IIS feature command.   If you are still having an issue, please post a screen shot and we can troubleshoot your environment.  Thanks.

**Comment by givenscj** [comment]
Closing.
