### ISSUE TITLE
Error in execution of Jupyter Notebooks

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Security-baseline-on-Azure#53]
In [Exercise 5:- task:-5  step 7](https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-5-execute-jupyter-notebooks) in Jupiter notebook Getting started.ipynb while running following query getting the parsing error: 

Query:
  > %kql search in ({selected_table.value}) {selected_columns.value[0]}: '*local service' | take 5" 

Error Message : 
```
query execution error:
{
    "error": {
        "code": "BadArgumentError",
        "innererror": {
            "code": "SyntaxError",
            "innererror": {
                "code": "SYN0002",
                "line": 1,
                "message": "Query could not be parsed at ')' on line [1,48]",
                "pos": 48,
                "token": ")"
            },
            "message": "A recognition error occurred in the query."
        },
        "message": "The request had some invalid properties"
    }
}

```
Please take a look to the screenshot
![error](https://user-images.githubusercontent.com/53901647/79995459-e057b900-84d4-11ea-870d-69806e039207.PNG)

**Comment by akn9050** [comment]
I have raised an issue in notebook repository for this error:

Here is the update on the notebook
https:/github.com/Azure/Azure-Sentinel-Notebooks/issues/20

**Comment by akn9050** [comment]
Any update on this?

**Comment by timahenning** [comment]
Hi,

Let me check on this for you.

Tim

**Comment by givenscj** [comment]
Hi there, this is a part of an external repo which is from the Sentinel team.  They would need to resolve on their side.

**Comment by akn9050** [comment]
Hi @givenscj , I understood, it is from external repo, still we need to investigate it as we are using in MCW. Please let us know if anything can be done on this.

**Comment by givenscj** [comment]
Update: I have followed up and the referenced notebook is retired now.  After reviewing for other notebooks, they all have issues currently.  We are looking at re-writing them from scratch since the source repo has been so unreliable.

**Comment by akn9050** [comment]
hi @givenscj , thanks for the details. Looking forward for the new notebook.

**Comment by Gvashi** [comment]
Hi @givenscj , any update on new notebook?

**Comment by timahenning** [comment]
We are going to remove the references to the notebooks today or tomorrow while we find a substitute notebook.

**Comment by Gvashi** [comment]
Sounds good, will wait for your reply.
Thankyou @timahenning

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #59
