### ISSUE TITLE
EXERCISE 3 TASK 5 (MIGRATING TO AZURE KEY VAULT> TEST THE SOLUTION

### ISSUE THREAD

**Issue by akincode** [microsoft/MCW-Security-baseline-on-Azure#54]
After doing the same task, deleting resources and starting all over again, I can't get this to work. When I do the final point (**run the project and navigate to the above page**) It gives an error. I think the code or something is broken. It loads the http://localhost:24448 
![Screenshot (79)](https://user-images.githubusercontent.com/61356515/80286659-8d744080-8724-11ea-97f5-5b4d965d6433.png)

but does not load the http://localhost:24448/api/Users   I am quite sure I followed the instructions to the letter, I started all over again at least 3 times.

![Screenshot (80)](https://user-images.githubusercontent.com/61356515/80286664-96651200-8724-11ea-9576-73960eb11b5a.png)

**Comment by givenscj** [comment]
Hi, the text tells you that you will get an error.  This is due to the encryption of the column.  You can implement the steps manually to fix it (as specified in the lab docs), or you can utilize the provided solution that has all the steps completed.

**Comment by akincode** [comment]
Okay thanks @givenscj
