### ISSUE TITLE
Azure Pass issue

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Security-baseline-on-Azure#56]
Received this issue via email.  Please review & advise:

The Security Baseline on Azure lab does not work with the Azure Passes anymore and needs a few minor changes in the Before HOL template: (link to arm template)

![Annotation 1](https://user-images.githubusercontent.com/39317565/81024249-bd5bcc00-8e27-11ea-9a16-c7a6d700ce7b.png)

1.	The schema should be HTTPS not HTTP 

  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",

2.	The virtual machine types are not suitable and available for all subscriptions:

![Annotation 2 ](https://user-images.githubusercontent.com/39317565/81024264-c77dca80-8e27-11ea-9723-f51f99edd9a8.png) 

"virtualMachineSize": "Standard_D2_v2"
"vmSize": "Standard_DS1_v2"
"vmSize": "Standard_DS2_v2"
"vmSize": "Standard_DS1_v2"

I had to run the PowerShell command: 

Get-AzComputeResourceSku | where {$_.Locations -icontains "eastus2"}

and find available types for my partners and change the template (I used Standard_E2_v3 as they are available for the subscriptions) 
![Annotation 3](https://user-images.githubusercontent.com/39317565/81024293-db293100-8e27-11ea-9555-288cbd153bf5.png)

Wanted to let you know as many partners use the Azure Passes to run these labs 😊 

Best regards,

**Comment by givenscj** [comment]
Addressed in the last pull request.
