### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Security-baseline-on-Azure#57]

**Comment by givenscj** [comment]
Some items to potentially add:

- Linux VM and agent install.
- Adaptive Application Controls
- Custom notebook (mimic broken sentinel ones)
- Adaptive Network hardening
- File Integrity Monitoring

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #61
