### ISSUE TITLE
Issue with Exercise 5: Azure Sentinel Logging and Reporting - Task 3: Investigate a custom alert incident

### ISSUE THREAD

**Issue by gregwsynnex** [microsoft/MCW-Security-baseline-on-Azure#58]
I was recently testing the MCW-Security-baseline-on-Azure workshop. Everything was proceeding as expected until I got to Exercise 5: Azure Sentinel Logging and Reporting. I first ran into an issue with Task 1: Create a dashboard. During this Task; the instructions state "In the list of workbooks, select Azure Network Watcher, choose Save.". During this process; I noticed that the Azure Network Watcher workbook had a red circle with an x for the Required data types: AzureNetworkAnalytics_CL.  I was able to "resolve" this issue by updating my Log Analytics configuration. 

However, as I continued the workshop to Task 3: Investigate a custom alert incident I am now having another issues that I have not been able to resolve. Specifically, I cannot get any Incidents to appear as documented in Task 3: Investigate a custom alert incident. I am reviewing the Rule Query syntax provided in Task 2: Create an Analytics alert (since I assume this is the query that will generate the Incidents). I did notice that by using the "View query results" in the "Set Rule Login" setting that I received a "NO RESULTS FOUND" message. I was able to "correct" this by inserting the following argument into the query statement:" | where TimeGenerated > ago(48h)". This this added argument; I was able to get a single output result:  
10.2.0.4 | UserRule_DenyAll | 10.2.0.4 | 31,014-- | -- | -- | --
but I still do not have any Incidents to view in the Sentinel Threat management | Incident view.

Can someone help understand how to resolve this issue? I plan to use this workshop for a training in mid-June, if possible.

**Comment by DawnmarieDesJardins** [comment]
@timahenning @givenscj 
Added you to review and advise.  Planned presentation of the workshop is June 18th.  Thanks gents!

**Comment by givenscj** [comment]
Hi Greg, you adding "TimeGenerated > ago(48h)" tells me you may have stopped working on the lab and then came back another day?  The lab does have a window in which it is evaluating the events in log analytics and if there are no events, no alert will fire.  These are generated by running the port scan script in the VM.  You would need to go back and run it again and then you would see more results within the query timeframe.

**Comment by timahenning** [comment]
@gregwsynnex Hi Greg, do you have any further comments?  If not, we are going to close this issue.

Tim

**Comment by gregwsynnex** [comment]
Yes, I have been working on this workshop on and off but I was never able to get these alerts to fire.
I will be working on this lab again today.
To this point; I have attempted this lab twice. After my first attempt; I completely removed the first deployment and re-deployed the workshop. Neither time was any Alerts generated and I ran the port scan script numerous times.
I will reattempt the lab again today.
Any suggestions on how I can get the alerts to appear will be appreciated.

**Comment by givenscj** [comment]
Hi Greg,

I just ran through the lab.  It took about 15 minutes before the first logs came in, they were for the DBTRAFFICONLY nsg, then after about 30 minutes, the WEBTRAFFICONLY nsg logs started to show up.  It does seem slower than it used to be, not sure why.  But the alerts did eventually fire.  I'll make it a bit easier (yet less real world) in the steps by removing the Resource filter and change the results to be >0 in the alert.  That would fire as soon as the DBTRAFFICONLY logs show up.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #60
