### ISSUE TITLE
Dynamic data masking not working 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Security-baseline-on-Azure#62]
In exercise 2 task 3 after adding mask , it is not replacing number with xxxx
![image](https://user-images.githubusercontent.com/57964598/90646376-c47edc80-e254-11ea-8032-a093c9b1e88e.png)

**Comment by givenscj** [comment]
Hi there, can you verify you did all the steps correctly?  This feature and the steps are pretty solid, and I didn't see it not work the last time I ran through the labs.  If you have verified a second time, I can take a look at your setup sometime this week.

**Comment by himanshuahlawat31** [comment]
sure , will let you know once we test it again

**Comment by DawnmarieDesJardins** [comment]
@himanshuahlawat31 
Hello.  Closing this issue for now.  If you still have trouble, please reopen and advise so we can investigate.
