### ISSUE TITLE
portscanner.ps1 is failing 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Security-baseline-on-Azure#63]
in exercise 4 task1 when we run the script it is failing and throwing error as the requested url does not exist on the server

![image](https://user-images.githubusercontent.com/57964598/90646694-1e7fa200-e255-11ea-9a85-a7d5502c1b73.png)

**Comment by givenscj** [comment]
Updated to the new putty download.  Also added instructions if the version changes.
