### ISSUE TITLE
Issues faced while performing this workshop

### ISSUE THREAD

**Issue by bonzz** [microsoft/MCW-Security-baseline-on-Azure#64]
1) 
Since there is many UI/UX changes in azure portal,  there are many confusions on how to perform some steps so can you please check on that.

2)
https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-3-test-network-security-group-rules-2

in this particular task it is mentioned -> Port scan for port 1433 (SQL) to db-1 is successful, and web-1 is unsuccessful from the paw-1 machine.

but this didnt work for me.

3)
https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-5-execute-jupyter-notebooks

in this particular task , it is specifying to search for Getting Started with Azure Sentinel Notebooks but it does show any rsults image for reference

![image](https://user-images.githubusercontent.com/48308835/101815653-d955e780-3b45-11eb-8cb6-ed5f0f0fb065.png)

4)
https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-2-review-and-create-azure-blueprints

here in mentioned task -> step 12 , it is specifying to select this particular option -> Audit unrestricted network access to storage accounts

but that option is no longer available.

Can you please check into this.

thanks & regards
Bony

**Comment by akn9050** [comment]
Hi @DawnmarieDesJardins, @givenscj  @timahenning, we have workshop scheduled for 17th Dec, can we prioritize the content update for this lab, content looks very old w.r.t UI and steps.

**Comment by givenscj** [comment]
Hi, thanks for reporting.  The firewall port script was referencing wrong repo.  The getting started notebooks are there, I added screen shot to help out.  They did in fact change the name of that policy definition, I updated but also added note to select another if they change the name again in future.

Updates have been made and should committed by the 17th.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge or PR #65

**Comment by akn9050** [comment]
Hi @givenscj , are we going to make UI chnages as well before 17th.

**Comment by timahenning** [comment]
@akn9050 What UI changes need to be updated specifically?

**Comment by DawnmarieDesJardins** [comment]
@akn9050 - please give more information so we can review/advise.
Reopening issue for further investigation

**Comment by timahenning** [comment]
Closing this issue due to opening of #66.
