### ISSUE TITLE
UI/UX changes

### ISSUE THREAD

**Issue by bonzz** [microsoft/MCW-Security-baseline-on-Azure#66]
Hi All,

This issue is regarding that there are some UI/UX changes in azure and due to which it could cause confusions for the users to perform this particular workshop.

So we have forked the repo and made the changes in our repo. we have kept it for reference below :-

https://github.com/sumitmalik51/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md

Is it possible to make the changes in Microsoft repo with new screenshots and also with all the steps updated according to the new UI/UX of azure ?

* Another issue while performing this particular task below : -

    https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-5-execute-jupyter-notebooks

    * Here we will select the particular option as mentioned in the below step and after that we will click on launch notebook.
          ![image](https://user-images.githubusercontent.com/48308835/102321801-31587800-3fa4-11eb-9ee4-5629f52036e9.png)

    * When we click on launch notebook the below page will appear where we are asked to created the ML workspace, But in the guide it is not specified like so can you please update the steps accordingly in the repo so as to perform this task.
           ![image](https://user-images.githubusercontent.com/48308835/102322013-6cf34200-3fa4-11eb-8d7f-7ccfde0fa1fc.png)

It would be great, if you can run through the whole lab and check from your end.

Thanks 
Bony

**Comment by timahenning** [comment]
Hi @bonzz,

Thank you for opening this issue.  I was curious to see how out of date the lab was compared to Azure.  It appears this lab requires enough work to warrant a test fix.  Unfortunately, there isn't budget for significant work.  We will review for Q3 2021 test fix.

Tim

**Comment by bonzz** [comment]
Thank you @timahenning

**Comment by DawnmarieDesJardins** [comment]
Closing issue - workshop is retiring, archiving this repo
