### ISSUE TITLE
Issue facing while performing Exercise 2 task 2

### ISSUE THREAD

**Issue by bonzz** [microsoft/MCW-Security-baseline-on-Azure#67]
Hi ,

While performing this particular task (link is mentioned below)

https://github.com/microsoft/MCW-Security-baseline-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Security%20baseline%20on%20Azure.md#task-2-test-the-web-application-solution

We provided the correct value for the connection string and but we were facing issue while running the solution.

Could you please check this?

Also ,it would be really helpful if you could be more specific with the instructions for example, where to substitute the connection string in the web config file so that it could avoid confusion and also which value to be provided. It would be great if screenshots are provided.

Thanks
Bony

**Comment by DawnmarieDesJardins** [comment]
@givenscj @timahenning 
Any update on this?

**Comment by givenscj** [comment]
Hi there, we can update the screen shot to show the end of the line where the servername is.  In terms of your issue, we'd need more info (such as a screen shot or the error you were getting) in order to help out further.

**Comment by timahenning** [comment]
@bonzz Could you help us out with a screenshot?

**Comment by sumitmalik51** [comment]
Hello @timahenning, I am testing out this workshop today and will update you with the screenshot.

**Comment by sumitmalik51** [comment]
Hello @timahenning, there have no issues while doing this step. Thanks

**Comment by timahenning** [comment]
Thank you for the update.
