### ISSUE TITLE
Not able to add packet capture.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Security-baseline-on-Azure#68]
Hi,
While testing the workshop I am not able to add the packet capture in network watcher, I have tried reinstalling the extension multiple times. Getting this issue.
![image](https://user-images.githubusercontent.com/45102602/107228413-a7c4a400-6a42-11eb-9088-d6ff6c15de51.png)

**Comment by sumitmalik51** [comment]
Hello @timahenning , Is there have any update on the above issue?

**Comment by givenscj** [comment]
Hi @sumitmalik51,  I just added packet capture to a VM and it worked ok.  This isn't something that is used in the following labs exercises so you can proceed without it.  If you want to resolve the issue you are having, you will likely need to file a ticket with Azure Support as all these steps are basic\common Azure activities.
