### ISSUE TITLE
Lab needs to revalidate.

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Security-baseline-on-Azure#70]
This lab guide needs to revalidate as many places the instruction was not clear because of Azure updates, some of the steps need to removed from the lab guide. Most of the screenshots need to update as the Azure UI is changing regularly.

**Comment by timahenning** [comment]
Thank you @sumitmalik51.

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 
Hi Sumit.  This workshop is scheduled to retire effective 5/31/21.  Appreciate the heads up, but this will be changed to read only next week.

**Comment by sumitmalik51** [comment]
Hello @DawnmarieDesJardins , Thanks for the confirmation.
